Removed XDG_DATA_DIRS, XDG_CONFIG_DIRS, and XDG_RUNTIME_DIR from xdg-vars.sh, encountering issues with flatpaks not being automatically added to the path, simplified alacritty config

diff --git a/config/bash/bash_profile b/config/bash/bash_profile
--- a/config/bash/bash_profile
+++ b/config/bash/bash_profile
@@ -1,12 +1,20 @@
 #!/usr/bin/env bash
 # shellcheck source=/home/fcher/.bash_profile
 export BASH_SILENCE_DEPRECATION_WARNING=1
-# echo "hello there!"
-export SHELLENV_DIR="$HOME/.config/shellenv"
-source "$SHELLENV_DIR/xdg-vars.sh"
-source "$SHELLENV_DIR/xdg-ninja.sh"
-source "$SHELLENV_DIR/settings.sh"
+SHELLENV_DIR="$HOME/.config/shellenv"
+if [[ -d $SHELLENV_DIR ]]; then
+  export SHELLENV_DIR
+  source "$SHELLENV_DIR/xdg-vars.sh"
+  source "$SHELLENV_DIR/xdg-ninja.sh"
+  source "$SHELLENV_DIR/settings.sh"
+else
+  echo "$SHELLENV_DIR" not found
+  exit 1
+fi
 
 if [ -f ~/.bashrc ]; then
   source ~/.bashrc
+else
+  echo "~/.bashrc not found"
+  exit 1
 fi
